drop SEQUENCE Cities_seq;
drop SEQUENCE program_seq;
drop table user_hometown_cities;
drop table USER_CURRENT_CITIES;
drop table Participants;
drop table user_events;
drop table tags;
ALTER TABLE Photos
DROP CONSTRAINT fk_album_id;
alter table albums
drop CONSTRAINT fk_photo_inalbum;
drop table Albums;
drop table photos;
drop  table messages;
drop table Friends;
drop table Education;
drop table Programs;
drop table users;
drop table cities;
